In [123]:
import math
import pandas as pd

In [124]:
# Uzaklık hesabı için öklid fonksiyonu:

def oklid_distance(data1 :list, data2 :list):
  lenght = len(data1)
  if lenght != len(data2):
    raise ValueError("Veri noktalarının uzunlukları eşit olmalı.")

  sum = 0
  for i in range(lenght):
    sum += (data1[i] - data2[i])**2

  return math.sqrt(sum)

In [125]:
# Veri setinden alınan veriler listeye dönüştürülür:

data = pd.read_csv("diabetes.csv")
data2 = data.drop(["Outcome"], axis=1) # Bağımlı değişken kaldırıldı
list = data2.values.tolist()
list[0]

[6.0, 148.0, 72.0, 35.0, 0.0, 33.6, 0.627, 50.0]

In [126]:
# Öklid fonksiyonun testi

print(oklid_distance(list[0], list[0]))
print(oklid_distance(list[0], list[1]))
print(oklid_distance(list[0], list[2]))
print(oklid_distance(list[0], list[3]))

0.0
66.90348403483932
54.29633528149022
115.73012399544037

In [127]:
# Yeni istenen [example] verisinin listedeki en yakın olanları 
# bulunur ve küçükten büyüğe listelenir: 
data_new = None

def listToDataframe(array):
    global data_new
    list_sum = []

    for i in range(0, len(list)):
        list_sum.append(oklid_distance(array, list[i]))

    data_new = pd.DataFrame(list_sum, columns=["Distance"])
    data_new = pd.concat([data_new, data], axis=1)
    data_new = data_new.sort_values(["Distance"])
    return data_new

In [128]:
def knn(array):
    global data_new
    k = 5
    data_new = listToDataframe(array)
    # İlk k satırdaki "Outcome" alanını listeye atma
    outcome_list = data_new.head(k).loc[:, "Outcome"].tolist()

    # 1: hasta, 0: sağlıklı
    hasta = 0
    saglikli = 0

    for i in range(0, k):
        number = outcome_list[i]
        if number == 0:
            saglikli = saglikli + 1
        else:
            hasta = hasta + 1

    if saglikli > hasta:
        print("Kişi sağlıklı")
    else:
        print("Kişi hasta")

    # Listeyi yazdırma
    print(F"İlk {k} verideki sonuçlar", outcome_list,"\n")
    data_new

In [131]:
knn([0,127,80,37,210,36.3,0.804,23]) # Sağlıklı
knn([10,122,78,31,0,27.6,0.512,45]) # Sağlıklı
knn([8,133,72,0,0,32.9,0.27,39]) # Hasta
knn([4,134,72,0,0,23.8,0.277,60]) # Hasta

knn([1,189,60,23,846,30.1,0.398,59]) # Hasta
knn([7,196,90,0,0,39.8,0.451,41]) # Hasta
knn([2,141,58,34,128,25.4,0.699,24]) # Sağlıklı
knn([3,120,70,30,135,42.9,0.452,30]) # Sağlıklı
knn([9,57,80,37,0,32.8,0.096,41]) # Sağlıklı
knn([0,127,80,37,210,36.3,0.804,23]) # Sağlıklı
knn([1,87,68,34,77,37.6,0.401,24]) # Sağlıklı

Kişi sağlıklı
İlk 5 verideki sonuçlar [0, 0, 0, 0, 1]

Kişi hasta
İlk 5 verideki sonuçlar [0, 1, 1, 1, 0]

Kişi hasta
İlk 5 verideki sonuçlar [1, 1, 0, 0, 1]

Kişi sağlıklı
İlk 5 verideki sonuçlar [1, 0, 0, 0, 0]

Kişi hasta
İlk 5 verideki sonuçlar [1, 0, 0, 1, 1]

Kişi hasta
İlk 5 verideki sonuçlar [1, 0, 1, 1, 1]

Kişi sağlıklı
İlk 5 verideki sonuçlar [0, 1, 0, 0, 0]

Kişi sağlıklı
İlk 5 verideki sonuçlar [0, 0, 0, 0, 1]

Kişi sağlıklı
İlk 5 verideki sonuçlar [0, 0, 0, 0, 0]

Kişi sağlıklı
İlk 5 verideki sonuçlar [0, 0, 0, 0, 1]

Kişi sağlıklı
İlk 5 verideki sonuçlar [0, 0, 0, 0, 0]

In [130]:
data_new.head(8)

,Distance,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
562,0.000000,1,87,68,34,77,37.6,0.401,24,0
377,9.009532,1,87,60,37,75,37.2,0.509,22,0
457,11.990053,5,86,68,28,71,30.2,0.364,24,0
241,13.351106,4,91,70,32,88,33.1,0.446,22,0
544,13.541097,1,88,78,29,76,32.0,0.365,29,0
490,13.553302,2,83,65,28,66,36.8,0.629,24,0
208,16.564195,1,96,64,27,87,33.2,0.289,21,0
87,17.082621,2,100,68,25,71,38.5,0.324,26,0